# Starter pipeline

trigger:
  - main

pool:
  name: Default
  demands:
    - agent.os -equals MacOsMarco
  
#pool:
#  vmImage: ubuntu-latest
  
steps:
- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'devops-services'
    manifests: 'nginx-deployment.yaml'
