# Starter pipeline

trigger:
  - main

pool:
  name: MacOsMarco
#  demands:
#    - agent.os -equals MacOsMarcoAgentName
  
#pool:
#  vmImage: ubuntu-latest
  
steps:
- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'devops-services'
    manifests: 'nginx-deployment.yaml'
